# HaoNick 4.1.3 by Haoshoku
# Support: https://haoshoku.xyz/go/discord

settings:
  # Can be edited in messages.yml.
  join_message: true
  quit_message: true
  # Settings for keeping nick.
  keep_nick:
    active: true
    # Permission to keep the nick data
    permission: 'haonick.keep'
    # Data which should be kept.
    data:
      uuid: true
      tag: true
      skin: true
      game_profile_name: false
    # Want a random name on join?
    random_name_on_join: false
    # If you do not activate mysql connection, HaoNick will automatically keeps the nick of player within a file.
    mysql:
      active: false
      host: 'localhost'
      port: 3306
      database: 'database'
      username: 'root'
      password: 'password'
      table_name: 'nick'
  chat:
    # Bukkit has its own handling for chats. If you let it true, HaoNick cancels the event and use a broadcastMessage for chat instead.
    # It is good for plugins which is incompatible with the format of NickAPI.
    # If you want to use the original format of bukkit, you can disable this option.
    broadcast_message_instead_of_format: true
  tab:
    # HaoNick has an integrated scoreboard update timer. Could help for possible fixes. Restart is required.
    timer:
      active: false
      # Default: 60 Every minute all of the players scoreboard are gonna be refreshed. Decreasing this value may cause performance problems.
      update_interval: 60
    # HaoNick will get the players scoreboard if a new scoreboard has been created by another plugins. If not, he will create a new scoreboard.
    # If you want to use the main scoreboard, set it to false
    new_scoreboard: true
    # If HaoNick has problems with scoreboard handling, you can increase the value.
    # Perhaps after increasing this value, it may work with another scoreboard plugins
    # In ticks!
    # 1 second = 20 Ticks
    scoreboard_creation_time: 10
    # You can use the tab header and footer created by HaoNick. Of course you can disable it.
    # Credits for 1.8.8 method belongs to Zay.
    # Compatible with PlaceholderAPI.
    # Supported: %online% for online players, %maxPlayers% for max players and %name% for players name.
    header_and_footer:
      active: true
      header: "§aYour header can be edited within settings.yml of HaoNick folder"
      footer: "§cYour footer can be edited within settings.yml of HaoNick folder"
      # Header and footer will be updated every 10 minutes (default).
      # You can decrease this value if you want to add compatibility with other plugins.
      update_interval: 600
  # Set this to false if you have problems with PlaceHolderAPI & HaoNick.
  placeholder_support: true